"""Initial migration

Revision ID: 568565b69638
Revises: 
Create Date: 2025-05-30 17:02:05.545471

"""
from typing import Sequence, Union

from alembic import op # noqa: F401
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '568565b69638'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
